version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: vuln-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db

  flask:
    build: .
    container_name: vuln-flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:admin@mongo:27017/
    volumes:
      - .:/app

volumes:
  mongo-data:
