version: "3"
services:
  mongo:
    image: mongo:4.4
    container_name: vuln-mongo
    ports:
      - "27017:27017"

  flask:
    build: .
    container_name: vuln-flask
    ports:
      - "5000:5000"
    depends_on:
      - mongo
